apiVersion: configsync.gke.io/v1alpha1
kind: RootSync
metadata:
  name: my-cluster-config # Replace with a descriptive name
  namespace: config-management-system # Standard namespace for Config Sync resources
spec:
  git:
    repo: https://github.com/anupam-mishra/anupamtest # Replace with your Git repository URL
    branch: main # Replace with the branch containing your configurations (optional)
    dir:  # Replace with the directory containing cluster-scoped configurations
    auth: none # Update based on your authentication needs (e.g., secret reference for private repos)
  # Optional: Override resource filtering with a list of specific resources to manage
  # resources:
  #   - group: admissionregistration.k8s.io
  #     kind: ValidatingWebhookConfiguration
  #     name: my-validator
